export const SECTION_LIST_PAGE = '/'
export const USER_PAGE = '/user'
export const SECTION_PAGE = '/section/:sectionId'
export const REGISTRATION_PAGE = '/registration'
export const LOGIN_PAGE = '/login'